#! /bin/bash

SCRIPTDIR="$(dirname "$BASH_SOURCE")"
cd $SCRIPTDIR

python3 -m venv py_venv
source ./py_venv/bin/activate

python3 -m pip install selenium imgui[full] playsound undetected-chromedriver
